version: "3.9"
services:
  postgres-brt:
    container_name: buyraktar-pg
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - .pg/storage:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: buyraktar
